/** Maps investor slug → local image path */
export const investorImages: Record<string, string> = {
  "peter-schiff": "/images/investors/peter-schiff.jpg",
  "eric-sprott": "/images/investors/eric-sprott.jpg",
  "sprott-asset-management-funds": "/images/investors/sprott-asset-management.jpg",
  "ross-beaty": "/images/investors/ross-beaty.jpg",
  "frank-giustra": "/images/investors/frank-giustra.jpg",
  "rick-rule": "/images/investors/rick-rule.jpg",
  "john-hathaway": "/images/investors/john-hathaway.jpg",
  "ned-naylor-leyland": "/images/investors/ned-naylor-leyland.jpg",
  "pierre-lassonde": "/images/investors/pierre-lassonde.jpg",
  "doug-casey": "/images/investors/doug-casey.jpg",
  "marin-katusa": "/images/investors/marin-katusa.jpg",
  "nolan-watson": "/images/investors/nolan-watson.jpg",
  "lukas-lundin": "/images/investors/lukas-lundin.jpg",
  "thomas-kaplan": "/images/investors/thomas-kaplan.jpg",
  "grant-williams": "/images/investors/grant-williams.jpg",
  "mark-bristow": "/images/investors/mark-bristow.jpg",
  "david-garofalo": "/images/investors/david-garofalo.jpg",
  "keith-neumeyer": "/images/investors/keith-neumeyer.jpg",
  "bob-quartermaine": "/images/investors/bob-quartermaine.jpg",
  "tavi-costa": "/images/investors/tavi-costa.jpg",
  "brien-lundin": "/images/investors/brien-lundin.jpg",
  "rob-mcewen": "/images/investors/rob-mcewen.jpg",
};
